apiVersion: v1
kind: Service
metadata:
  name: talancdz-service
spec:
  selector:
    app: talancdz
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer
