apiVersion: v1
kind: Service
metadata:
  name: talanocr-service
spec:
  selector:
    app: talanocr
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
